name: crawl-fast

on:
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        brand: [TagVenue, HireSpace]
        shard: [1, 2]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run crawler
        env:
          JOB_TOKEN: ${{ secrets.JOB_TOKEN }}
          APPS_SCRIPT_WEBHOOK: ${{ secrets.APPS_SCRIPT_WEBHOOK }}
        run: |
          node crawler.js \
            --brand ${{ matrix.brand }} \
            --shard ${{ matrix.shard }} \
            --totalShards 2
