name: crawl-fast
on:
  workflow_dispatch:
  schedule:
    - cron: "7 1 * * *" # daily 01:07 UTC

jobs:
  shard:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        brand: [TagVenue, HireSpace]
        shard: [1,2] # start small to test; we'll scale later
    env:
      APPS_SCRIPT_WEBHOOK: ${{ secrets.APPS_SCRIPT_WEBHOOK }}
      JOB_TOKEN: ${{ secrets.JOB_TOKEN }}
      BRAND: ${{ matrix.brand }}
      PAGES_PER_SHARD: 5   # test small first
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci || npm i
      - run: npx playwright install --with-deps chromium

      - name: Compute page range for this shard
        id: pages
        run: |
          START=$(( ( (${{ matrix.shard }} - 1 ) * $PAGES_PER_SHARD ) + 1 ))
          END=$(( $START + $PAGES_PER_SHARD - 1 ))
          echo "start=$START" >> $GITHUB_OUTPUT
          echo "end=$END" >> $GITHUB_OUTPUT

      - name: Crawl
        env:
          START_PAGE: ${{ steps.pages.outputs.start }}
          END_PAGE: ${{ steps.pages.outputs.end }}
          DETAIL_CONCURRENCY: 8
          LIST_CONCURRENCY: 3
        run: node crawler.js
