name: crawl-fast

on:
  workflow_dispatch:
    inputs:
      brand:
        description: "Which brand to crawl (HireSpace | TagVenue | All)"
        required: true
        default: "All"

jobs:
  crawl:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm i

      - name: Run scraper
        env:
          SCRAPERAPI_KEY: ${{ secrets.SCRAPERAPI_KEY }}
          APPS_SCRIPT_WEBHOOK: ${{ secrets.APPS_SCRIPT_WEBHOOK }}
          JOB_TOKEN: ${{ secrets.JOB_TOKEN }}
        run: |
          echo "brand input = ${{ github.event.inputs.brand }}"
          if [ "${{ github.event.inputs.brand }}" = "HireSpace" ]; then
            npm run crawl:hirespace
          elif [ "${{ github.event.inputs.brand }}" = "TagVenue" ]; then
            npm run crawl:tagvenue
          else
            npm run crawl:both
          fi
