name: crawl-fast

on:
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Chromium
        run: npx playwright install --with-deps chromium

      - name: Run scraper
        env:
          APPS_SCRIPT_WEBHOOK: ${{ secrets.APPS_SCRIPT_WEBHOOK }}
          JOB_TOKEN: ${{ secrets.JOB_TOKEN }}
          SCRAPERAPI_KEY: ${{ secrets.SCRAPERAPI_KEY }}
        run: npm run crawl:all

      - name: Upload debug pages
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pages
          path: |
            tagvenue-p*.png
            tagvenue-p*.html
            hirespace-p*.png
            hirespace-p*.html
