name: crawl-fast

on:
  workflow_dispatch:

jobs:
  shard:
    name: shard (${{ matrix.brand }}, ${{ matrix.shard }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        brand: [TagVenue, HireSpace]
        shard: [1, 2]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          npm ci || npm i

      - name: Install Playwright (Chromium + system deps)
        run: npx playwright install --with-deps chromium

      - name: Run crawler (diagnostics)
        env:
          BRAND: ${{ matrix.brand }}
          SHARD: ${{ matrix.shard }}
          SHARDS: 2
        run: node crawler.js

      - name: Upload page artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: page-artifacts-${{ matrix.brand }}-${{ matrix.shard }}
          path: artifacts/
          if-no-files-found: warn
